---
title: "Composer avec les technologies du web"
subtitle: "Genèses instrumentales collectives pour le développement d’une communauté de pratique de designers graphiques"
author: "Julie Blanc"
affiliation: "Université Paris 8 – ED&nbsp;224 / EnsadLab / EUR ArTeC"
object: "Thèse de doctorat en ergonomie"
bibliography: src/biblio/biblio.bib
csl: src/biblio/chicago-full-note.csl
---